name: Trigger auto deployment for swiftfiddle-runner-functions-311

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/swiftfiddle-runner-functions-311-AutoDeployTrigger-41d87636-81ab-41c6-a6e5-5ee429b68622.yml"

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: swiftfiddle.azurecr.io
          username: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS311_REGISTRY_USERNAME }}
          password: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS311_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: swiftfiddle.azurecr.io/swiftfiddle-runner-functions-311:latest
          file: ./Dockerfile
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS311_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n swiftfiddle-runner-functions-311 -g swiftfiddle --server swiftfiddle.azurecr.io --username  ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS311_REGISTRY_USERNAME }} --password ${{ secrets.SWIFTFIDDLERUNNERFUNCTIONS311_REGISTRY_PASSWORD }}
            az containerapp update -n swiftfiddle-runner-functions-311 -g swiftfiddle --image swiftfiddle.azurecr.io/swiftfiddle-runner-functions-311:latest
